language: php
php:
 - 5.4
 - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - mkdir -p build/logs
 - cd unittest/
 - phpunit unittest/TestAddingRestaurants.php
 - phpunit unittest/TestGettingRestaurants.php
