language: php
php:
 - 5.4
 - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - cd unittest/
 - mkdir -p build/logs
 - phpunit --coverage-text --coverage-clover build/logs/clover.xml TestAddingRestaurants
 - phpunit TestGettingRestaurants
